# rss downloader config file

[DEFAULT]
email: nikonor@nikonor.ru
smtp_login: rss-downloader@nikonor.ru
smtp_passwd: nmJQjSS4U0Nk
smtp_server: mail.nikonor.ru:465

[Lifehacker.ru]
url: https://lifehacker.ru/feed/
lastPubDate: 2026-09-16 16:46:48 +0300 +0300

[habr::golang]
url: https://habr.com/ru/rss/hub/go/all/?fl=ru
lastPubDate: 2026-09-16 17:00:04 +0000 MSK

[habr::rust]
url: https://habr.com/ru/rss/hub/rust/all/?fl=ru
lastPubDate: 2026-09-16 17:00:08 +0000 MSK
